[profile.default]
src = "/home/will/ghq/github.com/Will-Smith11/sks/src"
test = "/home/will/ghq/github.com/Will-Smith11/sks/test"
script = "/home/will/ghq/github.com/Will-Smith11/sks/script"
out = "/home/will/ghq/github.com/Will-Smith11/sks/out"
libs = ["/home/will/ghq/github.com/Will-Smith11/sks/lib"]
remappings = ["uniswap_v2_core/=/home/will/.sks/EpicTest/uniswap_v2_core/"]
auto_detect_remappings = true
libraries = []
cache = true
cache_path = "/home/will/ghq/github.com/Will-Smith11/sks/cache"
broadcast = "/home/will/ghq/github.com/Will-Smith11/sks/broadcast"
allow_paths = []
include_paths = []
force = false
evm_version = "paris"
gas_reports = ["*"]
gas_reports_ignore = []
auto_detect_solc = true
offline = false
optimizer = true
optimizer_runs = 200
verbosity = 0
ignored_error_codes = [
    "license",
    "code-size",
    "init-code-size",
]
deny_warnings = false
build_info = false
ffi = false
sender = "0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38"
tx_origin = "0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38"
initial_balance = "0xffffffffffffffffffffffff"
block_number = 1
gas_limit = 9223372036854775807
block_base_fee_per_gas = 0
block_coinbase = "0x0000000000000000000000000000000000000000"
block_timestamp = 1
block_difficulty = 0
block_prevrandao = "0x0000000000000000000000000000000000000000000000000000000000000000"
memory_limit = 33554432
extra_output = []
extra_output_files = []
names = false
sizes = false
via_ir = false
no_storage_caching = false
no_rpc_rate_limit = false
use_literal_content = false
bytecode_hash = "ipfs"
cbor_metadata = true
sparse_mode = false

[[profile.default.fs_permissions]]
access = "read"
path = "/home/will/ghq/github.com/Will-Smith11/sks/out"

[profile.default.rpc_storage_caching]
chains = "all"
endpoints = "all"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "preserve"
single_line_statement_blocks = "preserve"
override_spacing = false
wrap_comments = false
ignore = []
contract_new_lines = false

[doc]
out = "docs"
title = ""
book = "book.toml"
homepage = "README.md"
ignore = []

[fuzz]
runs = 256
max_test_rejects = 65536
dictionary_weight = 40
include_storage = true
include_push_bytes = true
max_fuzz_dictionary_addresses = 15728640
max_fuzz_dictionary_values = 6553600

[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
max_fuzz_dictionary_addresses = 15728640
max_fuzz_dictionary_values = 6553600
shrink_sequence = true
