[profile.default]
libs = ["lib"]
out = "out"
remappings = [
    "uniswap_v2_core/=/home/will/.sks/EpicTest/uniswap_v2_core/",
    "uniswap_v3_core/=/home/will/.sks/EpicTest/uniswap_v3_core/",
]
src = "src"
