#!/usr/bin/env bash
set -e

echo Installing sks...

BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
SKS_DIR=${FOUNDRY_DIR-"$BASE_DIR/.sks"}
SKS_BIN="$SKS_DIR/bin"


mkdir -p $SKS_BIN
chmod +x $SKS_BIN

echo Building sks
cargo build --release
mv ./target/release/sks $SKS_BIN


# Store the correct profile file (i.e. .profile for bash or .zshenv for ZSH).
case $SHELL in
*/zsh)
    PROFILE=${ZDOTDIR-"$HOME"}/.zshenv
    PREF_SHELL=zsh
    ;;
*/bash)
    PROFILE=$HOME/.bashrc
    PREF_SHELL=bash
    ;;
*/fish)
    PROFILE=$HOME/.config/fish/config.fish
    PREF_SHELL=fish
    ;;
*/ash)
    PROFILE=$HOME/.profile
    PREF_SHELL=ash
    ;;
*)
    echo "sks: could not detect shell, manually add ${SKS_BIN} to your PATH."
    exit 1
esac



if [[ ":$PATH:" != *":${SKS_BIN}:"* ]]; then
  echo "adding to path"
    echo >> $PROFILE && echo "export PATH=\"\$PATH:$SKS_BIN\"" >> $PROFILE
fi

# Warn MacOS users that they may need to manually install libusb via Homebrew:
if [[ "$OSTYPE" =~ ^darwin ]] && [[ ! -f /usr/local/opt/libusb/lib/libusb-1.0.0.dylib && ! -f /opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib ]]; then
    echo && echo "warning: libusb not found. You may need to install it manually on MacOS via Homebrew (brew install libusb)."
fi


